apiVersion: v1
kind: Service
metadata:
  name: keycloakpoc
  namespace: default
  labels:
    app: keycloakpoc
spec:
  selector:
    app: keycloakpoc
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
